# Save and Load trained model using
### 1) pickle <br>2) sklearn joblib

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn import linear_model

In [3]:
df = pd.DataFrame({
    'area' : [2600,3000,3200,3600,4000],
    'bedroom': [3,4,3,3,5],
    'age' :  [20,15,18,30,8],
    'price' : [550000,565000,610000,595000,760000]
})
df

area  bedroom  age   price
0  2600        3   20  550000
1  3000        4   15  565000
2  3200        3   18  610000
3  3600        3   30  595000
4  4000        5    8  760000

In [4]:
# Training a model
model = linear_model.LinearRegression()
model.fit(df[['area', 'bedroom', 'age']], df.price)

LinearRegression()

In [5]:
model.coef_  

array([   137.25, -26025.  ,  -6825.  ])

In [6]:
model.intercept_

383724.9999999998

In [7]:
model.predict([[5000 , 5 , 8]])

array([885250.])

In [8]:
# Save model
import pickle

In [9]:
with open('model_pickle', 'wb') as f:         # it create a module 'model_pickle' and saves model in it   # write binary mode
    pickle.dump(model,f)

In [10]:
with open('model_pickle', 'rb') as f:         # opening model in read binary mode
    model = pickle.load(f)                    # load model 

In [11]:
model.predict([[5000 , 5 , 8]])

array([885250.])

### joblib
*if our model have large numpy array then use joblib*

In [12]:
from sklearn.externals import joblib

ImportError: cannot import name 'joblib' from 'sklearn.externals' (C:\ProgramData\Anaconda3\lib\site-packages\sklearn\externals\__init__.py)

In [13]:
import joblib          # if previous import not work use this

In [14]:
joblib.dump(model,'model_joblib')

['model_joblib']

In [15]:
mj = joblib.load('model_joblib')

In [16]:
mj.predict([[5000 , 5 , 8]])

array([885250.])