<br>


### categorial

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [3]:
# handle TEXT data in numeric model
df = pd.DataFrame({
    'city' : ['delhi', 'delhi', 'delhi', 'delhi', 'pune', 'pune', 'pune', 'pune', 'mumbai', 'mumbai', 'mumbai', 'mumbai'],
    'area' : [  2600 ,  3000  ,  3200  ,  3400  ,  3600 ,  4000 ,  2600 ,  3000 ,   3400  ,   3200  ,   3600  ,   4000  ],
    'price': [ 550000, 778000, 610000 , 720000 , 725000, 550000, 565000, 610000,  720000 ,  660000  ,  725000 ,   700000]
})
df

city  area   price
0    delhi  2600  550000
1    delhi  3000  778000
2    delhi  3200  610000
3    delhi  3400  720000
4     pune  3600  725000
5     pune  4000  550000
6     pune  2600  565000
7     pune  3000  610000
8   mumbai  3400  720000
9   mumbai  3200  660000
10  mumbai  3600  725000
11  mumbai  4000  700000

if we encode name of cities as numbers (delhi=1 pune=2 mumbai=3) model can consider them like small and big<br>
(pune>delhi) which makes no sense

**Categorical variable**
1) Nominal  (city_name , Gender)     $\:\:\:\:\:\:\:\:\:\:\:\:\:\:\:\:\:\:\:\:\:\:\:\:$ 2) ordinal $\:\:\:$(high_medium_low , rating(good better best) )

#### Get Dummy

In [4]:
# add dummy variables
dumies = pd.get_dummies(df.city)
dumies

delhi  mumbai  pune
0       1       0     0
1       1       0     0
2       1       0     0
3       1       0     0
4       0       0     1
5       0       0     1
6       0       0     1
7       0       0     1
8       0       1     0
9       0       1     0
10      0       1     0
11      0       1     0

In [5]:
merged = pd.concat([df, dumies], axis='columns')
merged

city  area   price  delhi  mumbai  pune
0    delhi  2600  550000      1       0     0
1    delhi  3000  778000      1       0     0
2    delhi  3200  610000      1       0     0
3    delhi  3400  720000      1       0     0
4     pune  3600  725000      0       0     1
5     pune  4000  550000      0       0     1
6     pune  2600  565000      0       0     1
7     pune  3000  610000      0       0     1
8   mumbai  3400  720000      0       1     0
9   mumbai  3200  660000      0       1     0
10  mumbai  3600  725000      0       1     0
11  mumbai  4000  700000      0       1     0

In [ ]:
#****************   DROP ONE OF THE DUMMY COLUMN  ( TO PREVENT FROM MULTI COLINEARITY )

In [6]:
final = merged.drop(['city', 'pune'], axis='columns')          # dont need city column now
final

area   price  delhi  mumbai
0   2600  550000      1       0
1   3000  778000      1       0
2   3200  610000      1       0
3   3400  720000      1       0
4   3600  725000      0       0
5   4000  550000      0       0
6   2600  565000      0       0
7   3000  610000      0       0
8   3400  720000      0       1
9   3200  660000      0       1
10  3600  725000      0       1
11  4000  700000      0       1

In [7]:
from sklearn.linear_model import LinearRegression
model = LinearRegression()

In [8]:
x = final.drop('price', axis=1)
x

area  delhi  mumbai
0   2600      1       0
1   3000      1       0
2   3200      1       0
3   3400      1       0
4   3600      0       0
5   4000      0       0
6   2600      0       0
7   3000      0       0
8   3400      0       1
9   3200      0       1
10  3600      0       1
11  4000      0       1

In [9]:
y = final.price
y

0     550000
1     778000
2     610000
3     720000
4     725000
5     550000
6     565000
7     610000
8     720000
9     660000
10    725000
11    700000
Name: price, dtype: int64

In [10]:
model.fit(x,y)

LinearRegression()

In [11]:
model.predict([[5000, 1, 0]])                        # 1 0 means delhi       # 0 1 means mumbai   # 0 0 means pune

array([762366.93548387])

### Label Encoding

First use label encoding on categorical Data then apply one-Hot Encoding on them

In [12]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

In [13]:
df_le = df
le.fit_transform(df_le.city)                       #  delhi = 0     mumbai = 2     pune = 1

array([0, 0, 0, 0, 2, 2, 2, 2, 1, 1, 1, 1])

In [14]:
df_le.city=le.fit_transform(df_le.city)
df_le

city  area   price
0      0  2600  550000
1      0  3000  778000
2      0  3200  610000
3      0  3400  720000
4      2  3600  725000
5      2  4000  550000
6      2  2600  565000
7      2  3000  610000
8      1  3400  720000
9      1  3200  660000
10     1  3600  725000
11     1  4000  700000

In [15]:
x = df_le[['city', 'area']].values
x

array([[   0, 2600],
       [   0, 3000],
       [   0, 3200],
       [   0, 3400],
       [   2, 3600],
       [   2, 4000],
       [   2, 2600],
       [   2, 3000],
       [   1, 3400],
       [   1, 3200],
       [   1, 3600],
       [   1, 4000]], dtype=int64)

In [16]:
y=df_le.price
y

0     550000
1     778000
2     610000
3     720000
4     725000
5     550000
6     565000
7     610000
8     720000
9     660000
10    725000
11    700000
Name: price, dtype: int64

#### One Hot Encoding
*to deal with nominal categorical variable*

In [17]:
# from sklearn.preprocessing import OneHotEncoder
# ohe = OneHotEncoder(categorical_features=[0])  
# x = ohe.fit_transform(x).toarray()
# x
# **********     IF THIS DONT WORK   ***********************

# OneHotEncoder
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
ohe = ColumnTransformer([('encoder', OneHotEncoder(), [0])],     remainder='passthrough')
x = ohe.fit_transform(x)
x

array([[1.0e+00, 0.0e+00, 0.0e+00, 2.6e+03],
       [1.0e+00, 0.0e+00, 0.0e+00, 3.0e+03],
       [1.0e+00, 0.0e+00, 0.0e+00, 3.2e+03],
       [1.0e+00, 0.0e+00, 0.0e+00, 3.4e+03],
       [0.0e+00, 0.0e+00, 1.0e+00, 3.6e+03],
       [0.0e+00, 0.0e+00, 1.0e+00, 4.0e+03],
       [0.0e+00, 0.0e+00, 1.0e+00, 2.6e+03],
       [0.0e+00, 0.0e+00, 1.0e+00, 3.0e+03],
       [0.0e+00, 1.0e+00, 0.0e+00, 3.4e+03],
       [0.0e+00, 1.0e+00, 0.0e+00, 3.2e+03],
       [0.0e+00, 1.0e+00, 0.0e+00, 3.6e+03],
       [0.0e+00, 1.0e+00, 0.0e+00, 4.0e+03]])

In [18]:
# Drop 1 column
x = x[:,1:]       # Drops zeroth column
x

array([[0.0e+00, 0.0e+00, 2.6e+03],
       [0.0e+00, 0.0e+00, 3.0e+03],
       [0.0e+00, 0.0e+00, 3.2e+03],
       [0.0e+00, 0.0e+00, 3.4e+03],
       [0.0e+00, 1.0e+00, 3.6e+03],
       [0.0e+00, 1.0e+00, 4.0e+03],
       [0.0e+00, 1.0e+00, 2.6e+03],
       [0.0e+00, 1.0e+00, 3.0e+03],
       [1.0e+00, 0.0e+00, 3.4e+03],
       [1.0e+00, 0.0e+00, 3.2e+03],
       [1.0e+00, 0.0e+00, 3.6e+03],
       [1.0e+00, 0.0e+00, 4.0e+03]])

In [19]:
model.fit(x, y)

LinearRegression()

In [20]:
model.predict([[1,0,0,2800]])          # 1,0,0 Means Delhi

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 4)