# Split Dataset into Training & Test dataset

In [5]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
model = LinearRegression()

In [6]:
df = pd.DataFrame({
    'area' : [  2600 ,  3000  ,  3200  ,  3400  ,  3600 ,  4000 ,  2600 ,  3000 ,   3400  ,   3200  ,   3600  ,   4000  ],
    'price': [ 550000, 778000 , 610000 , 720000 , 725000, 550000, 565000, 610000,  720000 ,  660000 ,  725000 ,   700000]
})
df

area   price
0   2600  550000
1   3000  778000
2   3200  610000
3   3400  720000
4   3600  725000
5   4000  550000
6   2600  565000
7   3000  610000
8   3400  720000
9   3200  660000
10  3600  725000
11  4000  700000

In [7]:
x = np.array(df.area).reshape(-1,1)            # *******************************************
y = df.price

In [8]:
x

array([[2600],
       [3000],
       [3200],
       [3400],
       [3600],
       [4000],
       [2600],
       [3000],
       [3400],
       [3200],
       [3600],
       [4000]], dtype=int64)

In [9]:
y

0     550000
1     778000
2     610000
3     720000
4     725000
5     550000
6     565000
7     610000
8     720000
9     660000
10    725000
11    700000
Name: price, dtype: int64

In [10]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2) 
# 20% is for test data  # we get 4 parameter in return  # on every reRun it choose random samples 
# use   random_state=10   as attribute to produce always same set of data

In [11]:
x_train 

array([[3400],
       [3200],
       [3400],
       [2600],
       [4000],
       [3600],
       [3200],
       [3000],
       [3600]], dtype=int64)

In [12]:
y_train

3     720000
2     610000
8     720000
6     565000
5     550000
4     725000
9     660000
1     778000
10    725000
Name: price, dtype: int64

In [13]:
x_test

array([[3000],
       [2600],
       [4000]], dtype=int64)

In [14]:
y_test

7     610000
0     550000
11    700000
Name: price, dtype: int64

In [15]:
model.fit(x_train, y_train)

LinearRegression()

In [16]:
model.predict(x_test)

array([670906.25      , 668927.08333333, 675854.16666667])

In [17]:
model.score(x_test, y_test)           # accuracy is 25%

-0.6172143602278277